POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Santosh K.C.",
  "email": "santoshkc776@gmail.com",
  "address": "Chapagaun,Lalitput",
  "dateOfBirth": "2002-03-06",
  "registeredDate": "2025-12-04"

}